In [1]:
import numpy as np

Creating a Matrix using NumPy

In [3]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
matrix_1.shape

(2, 2)

In [5]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [6]:
matrix_2.shape

(3, 3)

creating a Matrix with random values

In [7]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.41338717 0.11798859 0.82450458]
 [0.0193656  0.33983104 0.01625973]
 [0.02218676 0.6237352  0.78209645]]


In [9]:
# Creation of random matrix with integers

random_integer_matrix = np.random.randint(100 , size = (6,6))
print(random_integer_matrix)

[[15 48 27  2 85 64]
 [ 0 75 77 79 98 76]
 [ 1  8 46 79 41 78]
 [78 31 69 17  9 86]
 [11  5 45 39 91 53]
 [ 1 30 13 67 89 91]]


In [10]:
# Matrix with all the values as 1

matrix_3 = np.ones([5,5])
print(matrix_3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
matrix_3 = np.ones((5,5), dtype=str)
print(matrix_3)

[['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']]


In [13]:
# Null Matrix

null_matrix = np.zeros((5,5), dtype=int)
print(null_matrix)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [22]:
# Identity Matrix

identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
# Transpose of a Matrix

a = np.random.randint(100 , size = (5,5))
print(a)

[[36 29 38 41  8]
 [ 7 19 81 28 44]
 [19 53  8  6 23]
 [84 95 48 99 69]
 [40 84 89 12 39]]


In [25]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[36  7 19 84 40]
 [29 19 53 95 84]
 [38 81  8 48 89]
 [41 28  6 99 12]
 [ 8 44 23 69 39]]


# **Matrix Addtion.**

In [26]:
# Two Matrices can be added only if they have the same shape

a = np.random.randint(100 , size = (5,5))
b = np.random.randint(100 , size = (5,5))
print(a)
print(b)

[[22 34 45 56 32]
 [59 92 88 15 92]
 [ 5  4 67  6 55]
 [51 84 62 53 48]
 [ 9 65 56 63 85]]
[[97  5 57 27 33]
 [16 20 91  4 60]
 [51 40 17 45 76]
 [66 56 65 91 61]
 [66 78 41 64 77]]


In [30]:
a.shape

(5, 5)

In [31]:
b.shape

(5, 5)

In [32]:
sum =  np.add(a,b)
print(sum)

[[119  39 102  83  65]
 [ 75 112 179  19 152]
 [ 56  44  84  51 131]
 [117 140 127 144 109]
 [ 75 143  97 127 162]]


In [33]:
# create two matrices with random values

matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(20, size=(3,4))

sum_2 = np.add(matrix_3, matrix_4)
print(sum_2)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

We get this error because shape of matrix_3 and matrix_4 are different

# **Matrix Subtraction**

In [35]:

matrix_5 = np.random.randint(10, size=(3,3))
matrix_6 = np.random.randint(20, size=(3,3))

In [36]:
print(matrix_5)
print(matrix_6)

[[7 7 7]
 [3 4 1]
 [7 9 5]]
[[ 7 13  5]
 [19  1  4]
 [18  3  7]]


In [37]:
difference = np.subtract(matrix_5, matrix_6)
print(difference)

[[  0  -6   2]
 [-16   3  -3]
 [-11   6  -2]]


# **Matrix Multiplication**

In [38]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[8 4 0 9]
 [8 2 6 1]
 [5 7 2 8]
 [5 1 0 8]]


In [40]:
product = np.multiply(x,y)
print(product)

[[40 20  0 45]
 [40 10 30  5]
 [25 35 10 40]
 [25  5  0 40]]


In [41]:
# Multiplying 2 Matrices

matrix_7 = np.random.randint(5, size=(3,3))
matrix_8 = np.random.randint(5, size=(3,4))

print(matrix_7)
print(matrix_8)

[[0 1 3]
 [0 2 3]
 [4 0 3]]
[[2 1 3 2]
 [0 4 2 1]
 [0 1 2 3]]


In [42]:
product = np.dot(matrix_3, matrix_4)
print(product)

[[271 315 248 221]
 [205 243 199 186]
 [ 61  89  51  68]]


In [43]:
product.shape

(3, 4)